### ISSUE TITLE
bibtex显示无法指定第二个bibstyle和bibdata

### ISSUE THREAD

**Issue by ji-xin** [linhr/thuappendixbib#1]
在编译的第三步`bibtex main`的时候，bibtex显示

Illegal, another \bibstyle command---line 114 of file data/appendix01.aux
 : \bibstyle
 :          {thuthesis-numeric}
I'm skipping whatever remains of this command
Illegal, another \bibdata command---line 115 of file data/appendix01.aux
 : \bibdata
 :         {ref/app_refs}
I'm skipping whatever remains of this command

不知道是不是我哪里弄错了。

**Comment by ji-xin** [comment]
我是按着readme一步一步来的。唯一的区别是用了`\bibliographystyle{thuthesis-numeric}`而不是`\bibliographystyle{thubib}`，因为并没有thubib.bst。

**Comment by linhr** [comment]
我用最新版的 ThuThesis 和 TeXLive 试了一下，的确可以复现这个错误。这个宏包是 4 年前写的了，我现在不确定在当时的编译环境下是否也有这个问题出现。

根据错误信息并结合网上关于 chapterbib 的一些讨论，这个错误似乎是可以忽略的。所以按照 README 继续执行之后的命令可生成最终的 PDF。

如果使用 Makefile，可在 `bibtex main` 命令前添加 `-` 忽略其错误，如下所示。

```
main.pdf
	xelatex main
	bibtex data/appendix01
	-bibtex main
	xelatex main
	xelatex main
```

尽管该错误可忽略，但由于 `bibtex main` 返回非 0 值，latexmk 将提前终止从而导致编译失败。所以目前暂时无法使用 latexmk 自动完成整个编译过程。

**Comment by ji-xin** [comment]
ok多谢！
